# Generated by Django 2.0.3 on 2018-04-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('viber_id', models.IntegerField()),
                ('role', models.CharField(choices=[('USER', 'User'), ('SU_USER', 'Superuser'), ('NEW_USER', 'New user'), ('ADMIN', 'Admin'), ('BLACK', 'Blacklist user')], default='BLACK', max_length=8)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
