# Generated by Django 2.0.3 on 2018-04-23 21:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('py_viber', '0001_initial'), ('py_viber', '0002_auto_20180420_0041'), ('py_viber', '0003_auto_20180422_1714'), ('py_viber', '0004_auto_20180422_1718'), ('py_viber', '0005_auto_20180422_1724')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('viber_id', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('USER', 'User'), ('SU_USER', 'Superuser'), ('NEW_USER', 'New user'), ('VALID', 'Valid user'), ('VALID_VERIF', 'Valid user verif'), ('VALID_GOOD', 'Valid good'), ('SU_VALID', 'Super valid user'), ('ADMIN', 'Admin'), ('BLACK', 'Blacklist user')], default='NEW_USER', max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Пользователи',
                'verbose_name': 'Пользователь',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('READY', 'Ждет отправления'), ('POST', 'Отправлено')], default='READY', max_length=6)),
                ('date_status', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='py_viber.User')),
            ],
            options={
                'verbose_name_plural': 'Сообщения',
                'verbose_name': 'Сообщение',
            },
        ),
    ]
