# Generated by Django 2.0.3 on 2018-04-20 00:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('py_viber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('READY', 'Ждет отправления'), ('POST', 'Отправлено')], default='READY', max_length=6)),
                ('date_status', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('SU_USER', 'Superuser'), ('NEW_USER', 'New user'), ('ADMIN', 'Admin'), ('BLACK', 'Blacklist user')], default='NEW_USER', max_length=8),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='py_viber.User'),
        ),
    ]
