# Generated by Django 2.0.3 on 2018-04-23 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('py_viber', '0002_auto_20180423_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='viber_chart',
        ),
    ]
