# Generated by Django 2.0.3 on 2018-04-23 22:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('py_viber', '0003_remove_user_viber_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='key',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
