# Generated by Django 2.0.3 on 2018-04-04 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('py_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_stop', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_stop', models.TimeField()),
                ('stop_equipment', models.BooleanField()),
                ('text', models.TextField(max_length=200)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='py_site.Machine')),
                ('user_start', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='py_site.User')),
            ],
        ),
    ]
