# Generated by Django 2.0.3 on 2018-04-04 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('py_site', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user_stop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='py_site.User'),
        ),
    ]
