# Generated by Django 2.0.3 on 2018-03-25 21:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('si8_parsing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('READY', 'Запись добавлена, но еще не подтверждена'), ('RUN', 'Запись в работе'), ('DELETE', 'Для записи запрошено удаление')], max_length=4)),
            ],
            options={
                'verbose_name_plural': 'Избранные',
                'verbose_name': 'Избронное',
            },
        ),
        migrations.CreateModel(
            name='Loop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('READY', 'Запись добавлена, но еще не подтверждена'), ('RUN', 'Запись в работе'), ('DELETE', 'Для записи запрошено удаление')], default='RUN', max_length=6)),
                ('trigger_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('trigger_value', models.IntegerField(default=0)),
                ('trigger_hysteresis', models.IntegerField(default=0)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='si8_parsing.Machine')),
            ],
            options={
                'verbose_name_plural': 'Петли',
                'verbose_name': 'Петля',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('READY', 'Ждет отправления'), ('POST', 'Отправлено')], default='READY', max_length=6)),
                ('date_status', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Сообщения',
                'verbose_name': 'Сообщение',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('telegram_id', models.IntegerField()),
                ('role', models.CharField(choices=[('USER', 'User'), ('SU_USER', 'Superuser'), ('NEW_USER', 'New user'), ('ADMIN', 'Admin'), ('BLACK', 'Blacklist user')], default='USER', max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Пользователи',
                'verbose_name': 'Пользователь',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='py_telegram.User'),
        ),
        migrations.AddField(
            model_name='loop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='py_telegram.User'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='py_telegram.User'),
        ),
    ]
