# Generated by Django 2.0.3 on 2019-06-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si8_parsing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_name', models.CharField(blank=True, default='/dev/ttyUSB0', max_length=20, null=True)),
                ('baud_rate', models.IntegerField(default=4800)),
            ],
            options={
                'verbose_name': 'Сом порт',
            },
        ),
    ]
