# Generated by Django 2.0.3 on 2019-06-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si8_parsing', '0002_comport'),
    ]

    operations = [
        migrations.AddField(
            model_name='comport',
            name='enable',
            field=models.BooleanField(default=False),
        ),
    ]
