# Generated by Django 2.0.3 on 2019-06-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('si8_parsing', '0004_machine_comport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='comport',
            new_name='com_port',
        ),
    ]
