# Generated by Django 2.0.3 on 2019-06-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si8_parsing', '0005_auto_20190607_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='comport',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
