# Generated by Django 2.0.3 on 2019-06-27 13:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('si8_parsing', '0006_comport_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='status',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
