# Generated by Django 2.0.3 on 2019-07-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si8_parsing', '0009_comport_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='enable',
            field=models.BooleanField(default=False),
        ),
    ]
