# Generated by Django 2.0.3 on 2019-07-31 21:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si8_parsing', '0010_machine_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='norma_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='normative_product',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='normative_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='value',
            name='value',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
