# Generated by Django 2.0.3 on 2019-07-31 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si8_parsing', '0011_auto_20190731_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='norma_speed',
        ),
        migrations.AddField(
            model_name='machine',
            name='normative_speed',
            field=models.IntegerField(default=0),
        ),
    ]
