# Generated by Django 2.0.3 on 2019-07-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si8_parsing', '0012_auto_20190731_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='normative_product',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='machine',
            name='normative_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='machine',
            name='normative_time',
            field=models.FloatField(default=0),
        ),
    ]
