# Generated by Django 2.0.3 on 2019-08-01 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si8_parsing', '0014_remove_machine_normative_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='normative_time',
            field=models.TimeField(default=datetime.datetime(2019, 8, 1, 21, 10, 48, 54079)),
            preserve_default=False,
        ),
    ]
