# Generated by Django 2.0.3 on 2019-08-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si8_parsing', '0016_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
